# Generated by Django 4.2.2 on 2023-07-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dui', models.CharField(blank=True, help_text='Ingrese número de DUI sin guiones', max_length=100)),
                ('nombre_encargado', models.CharField(blank=True, help_text='Ingrese un nombre válido', max_length=60, null=True)),
                ('apellido_encargado', models.CharField(max_length=60)),
                ('fecha_nacimiento_encargado', models.DateField(blank=True, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=60, null=True)),
                ('dui_madre', models.CharField(blank=True, max_length=60, null=True)),
                ('ocupacion_madre', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre_padre', models.CharField(blank=True, max_length=60, null=True)),
                ('dui_padre', models.CharField(blank=True, max_length=60, null=True)),
                ('ocupacion_padre', models.CharField(blank=True, max_length=60, null=True)),
                ('alumno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_alumnos.alumno')),
            ],
        ),
    ]
