# Generated by Django 4.2.2 on 2023-07-26 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateField(default=datetime.datetime.now)),
                ('direccion_actual', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono_actual_casa', models.CharField(blank=True, max_length=60, null=True)),
                ('ultimo_centro_de_estudio', models.CharField(blank=True, max_length=60, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
